### PR TITLE
Fix temporary file issue in s3

### LINKED ISSUE #1519: S3 driver creates temporary files in current directory
As a result if a process is executed on an environment where whole FS is read-only except `/tmp` directory - uploading to S3 fails with `Could not append to the internal temporary file`.

That's not the case with GCS which tries to find tmp dir:
https://github.com/tensorflow/io/blob/6110049ff73ed5dc85046737f71057401b679eac/tensorflow_io_gcs_filesystem/core/gcs_helper.cc#L46 =>
https://github.com/tensorflow/tensorflow/blob/17774a11b576186e439174298af82b096dcd5582/tensorflow/core/platform/path.cc#L329

Compare with S3 which just passes null prefix downstream:
https://github.com/tensorflow/io/blob/6110049ff73ed5dc85046737f71057401b679eac/tensorflow_io/core/filesystems/s3/s3_filesystem.cc#L358

TF S3 implementation just uses `/tmp`:
https://github.com/tensorflow/tensorflow/blob/17774a11b576186e439174298af82b096dcd5582/tensorflow/core/platform/s3/s3_file_system.cc#L57

Quick workaround can be to `os.chdir("/tmp")` if acceptable.

### PR DESCRIPTION
**Pull request by yongtang**
This PR tries to fix the temporary file issue in s3 where temp files are created within the current directory.

This PR maintains the behavior of old s3 file system.

This PR fixes #1519.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

File: tensorflow_io/core/filesystems/s3/s3_filesystem.cc [hunk 1]
```diff
@@ -355,9 +355,15 @@ typedef struct S3File {
         s3_client(s3_client),
         transfer_manager(transfer_manager),
         outfile(Aws::MakeShared<Aws::Utils::TempFile>(
-            kS3FileSystemAllocationTag, nullptr, "_s3_filesystem_XXXXXX",
+            kS3FileSystemAllocationTag,
+#if defined(_MSC_VER)
+            nullptr,
```
Comment (kvignesh1420) [inline tensorflow_io/core/filesystems/s3/s3_filesystem.cc:360]: @yongtang where will be the temporary files be created if it is a nullptr?

**Comment by yongtang** [comment]
@kvignesh1420 The temp file will be on the same directory on Windows. Added a comment in the code which matches:
https://github.com/tensorflow/tensorflow/blob/17774a11b576186e439174298af82b096dcd5582/tensorflow/core/platform/s3/s3_file_system.cc#L52-L58

**Review by kvignesh1420 — APPROVED** [review]
LGTM. Thanks @yongtang
